AllCops:
  Exclude:
    - db/schema.rb
    - config/**
    - features/**
    - db/migrate/**
    - lib/arel_node_match_postgres_ext.rb

Layout/MultilineOperationIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
