script: "rake -v travis"
before_script:
  - "export JRUBY_OPTS='-Xcompile.invokedynamic=true'"
  - "cp -v config/travis/database.yml.travis.${TRAVIS_RUBY_VERSION}.${DB} config/database.yml"
  - "rake db:create db:migrate"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

gemfile:
  - Gemfile
  - gemfiles/Gemfile.jruby


matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.jruby
      env: DB=mysql
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.jruby
      env: DB=postgres
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.jruby
      env: DB=sqlite
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.jruby
      env: DB=mysql
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.jruby
      env: DB=postgres
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.jruby
      env: DB=sqlite
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.jruby
      env: DB=mysql
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.jruby
      env: DB=postgres
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.jruby
      env: DB=sqlite
    - rvm: jruby-19mode
      gemfile: Gemfile
      env: DB=mysql
    - rvm: jruby-19mode
      gemfile: Gemfile
      env: DB=postgres
    - rvm: jruby-19mode
      gemfile: Gemfile
      env: DB=sqlite
    - rvm: jruby-head
      gemfile: Gemfile
      env: DB=mysql
    - rvm: jruby-head
      gemfile: Gemfile
      env: DB=postgres
    - rvm: jruby-head
      gemfile: Gemfile
      env: DB=sqlite
    - rvm: jruby-head
      gemfile: gemfiles/Gemfile.jruby
      env: DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/Gemfile.jruby
      env: DB=postgres
    - rvm: ruby-head
      gemfile: Gemfile
      env: DB=mysql
    - rvm: ruby-head
      gemfile: Gemfile
      env: DB=postgres
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

