defaults: &defaults
  product_name: 家計簿 さな太郎
  system_mail_address: donotreply@nu-chon.org
  effect:
    pulsate:
      duration: 300
      times: 3
    fade:
      duration: 300
    slide:
      duration: 200
    highlight:
      duration: 1000
      color: "#ff99ff"
  item_list_count: 20
  enable_tweet: true
  api_auth:
    oauth: true
    basic: false
    session: true

development:
  <<: *defaults
  item_list_count: 100
  admin_user: "admin"
  admin_password: "password"
  oauth_admin_user: "admin"
  oauth_admin_password: "password"
  secret_token: "0037d0aae72d93c8a8574861fe18ea3e7d9bf70220a4832e6528b8c0d7d5a66e5630b12ab7993913fc8b149dfe2ebd9b0e102b064d5efcd76a2f90af9e1c8fbb"

test:
  <<: *defaults
  api_auth:
    oauth: true
    basic: true
    session: true
  secret_token: "0037d0aae72d93c8a8574861fe18ea3e7d9bf70220a4832e6528b8c0d7d5a66e5630b12ab7993913fc8b149dfe2ebd9b0e102b064d5efcd76a2f90af9e1c8fbb"
  
production:
  <<: *defaults
  item_list_count: 200
